language: php

php:
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"

env:
  - COMPOSER_FLAGS=""
  - COMPOSER_FLAGS="--prefer-lowest"

matrix:
  fast_finish: true


install:
  - composer update ${COMPOSER_FLAGS} --prefer-source